api_platform:
    title: 'API Gestion des Kits'
    description: 'Stockage et traçabilité des péremptions des kits'
    version: '2.1.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: X-AUTH-TOKEN
                type: header
    formats:
        json:
            mime_types: ['application/json']
            
        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']
    defaults:
        pagination_enabled: false
